---

- name: Download Elasticsearch package
  become: yes
  get_url:
    dest: "/usr/local/src/elasticsearch-{{ sansible_elasticsearch_version }}.deb"
    url: "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{ sansible_elasticsearch_version }}.deb"

- name: Install Elasticsearch
  become: yes
  apt:
    deb: "/usr/local/src/elasticsearch-{{ sansible_elasticsearch_version }}.deb"
    state: present
  notify: restart elasticsearch

- name: Install Elasticsearch 1.x plugins
  become: yes
  command: "/usr/share/elasticsearch/bin/plugin -install {{ item.plugin_name }}"
  args:
    chdir: /usr/share/elasticsearch/
    creates: "/usr/share/elasticsearch/plugins/{{ item.plugin_dir | default(item.plugin_name) }}"
  environment:
    JAVA_HOME: /usr/share/java
  with_items: "{{ sansible_elasticsearch_plugins }}"

- name: Set ElasticSearch Startup Timeout
  become: yes
  lineinfile:
    path: /etc/init.d/elasticsearch
    regexp: "timeout=10"
    line: "                timeout={{ sansible_elasticsearch_startup_timeout }}"
  notify: restart elasticsearch
  when: sansible_elasticsearch_startup_timeout != None
