---

- name: Add Elastic gpg key
  become: yes
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Elasticsearch repo
  become: yes
  apt_repository:
    repo: "deb http://packages.elasticsearch.org/elasticsearch/{{ sansible_elasticsearch_family }}/debian stable main"
    state: present

- name: Install Elasticsearch
  become: yes
  apt:
    name: "elasticsearch={{ sansible_elasticsearch_version }}"
    state: present
  notify: restart elasticsearch

- name: Install Elasticsearch 2.x plugins
  become: yes
  command: "/usr/share/elasticsearch/bin/plugin install {{ item.plugin_name }}"
  args:
    chdir: /usr/share/elasticsearch/
    creates: "/usr/share/elasticsearch/plugins/{{ item.plugin_dir | default(item.plugin_name) }}"
  environment:
    JAVA_HOME: /usr/share/java
  with_items: "{{ sansible_elasticsearch_plugins }}"

- name: Set ElasticSearch Startup Timeout
  become: yes
  lineinfile:
    path: /etc/init.d/elasticsearch
    regexp: "timeout=10"
    line: "                timeout={{ sansible_elasticsearch_startup_timeout }}"
  notify: restart elasticsearch
  when: sansible_elasticsearch_startup_timeout != None
