---

- name: Add Elastic gpg key
  become: yes
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Elasticsearch repo
  become: yes
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ sansible_elasticsearch_family }}/apt stable main"
    state: present

- name: Install Elasticsearch
  become: yes
  apt:
    name: "elasticsearch={{ sansible_elasticsearch_version }}"
    state: present
  notify: restart elasticsearch

- name: Install Elasticsearch 5.x plugins
  become: yes
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install {{ item.plugin_name }}"
  args:
    chdir: /usr/share/elasticsearch/
    creates: "/usr/share/elasticsearch/plugins/{{ item.plugin_dir | default(item.plugin_name) }}"
  environment:
    JAVA_HOME: /usr/share/java
  with_items: "{{ sansible_elasticsearch_plugins }}"
