---

- name: Raise open file limits for elasticsearch and allow memory locking
  become: yes
  template:
    src: 10-elasticsearch.conf
    dest: /etc/security/limits.d/10-elasticsearch.conf
    backup: yes
  notify:
    - restart elasticsearch

- name: Ensure sysctl.conf settigns
  become: yes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ sansible_elasticsearch_sysctl }}"
  when: ansible_virtualization_type != "docker"

- name: Setup environment variables
  become: yes
  template:
    src: "{{ sansible_elasticsearch_family }}/elasticsearch.default.j2"
    dest: /etc/default/elasticsearch
    backup: true
  notify:
    - restart elasticsearch

- name: Configure elasticsearch
  become: yes
  template:
    src: "elasticsearch.yml.j2"
    dest: /etc/elasticsearch/elasticsearch.yml
    backup: true
  notify:
    - restart elasticsearch

- name: Create AWS Snapshot script
  become: yes
  template:
    dest: "/home/{{ sansible_elasticsearch_user }}/bin/aws_s3_snapshot.sh"
    group: "{{ sansible_elasticsearch_group }}"
    mode: 0750
    owner: "{{ sansible_elasticsearch_user }}"
    src: aws_s3_snapshot.sh.j2
  when: sansible_elasticsearch_s3_backup_enabled == true

- name: Ensure Elasticsearch service is started
  become: yes
  service:
    name: elasticsearch
    state: started
