---

- name: Setup environment variables
  become: yes
  template:
    src: elasticsearch.default.j2
    dest: /etc/default/elasticsearch
    backup: true
  notify:
    - restart elasticsearch

- name: Raise open file limits for elasticsearch and allow memory locking
  become: yes
  copy:
    src: 10-elasticsearch.conf
    dest: /etc/security/limits.d/10-elasticsearch.conf
    backup: yes
  notify:
    - restart elasticsearch

- name: Configure elasticsearch
  become: yes
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    backup: true
  notify:
    - restart elasticsearch

- name: Create AWS Snapshot script
  become: yes
  template:
    dest: "/home/{{ elasticsearch.user }}/bin/aws_s3_snapshot.sh"
    group: "{{ elasticsearch.user }}"
    mode: 0750
    owner: "{{ elasticsearch.user }}"
    src: aws_s3_snapshot.sh.j2
  when: elasticsearch.plugin_config.aws.s3_backup.enabled

- name: Ensure Elasticsearch service is started
  become: yes
  service:
    name: elasticsearch
    state: started
