---

- name: Install Elasticsearch extra packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ sansible_elasticsearch_packages }}"
  notify: restart elasticsearch

- name: Install apt packages for SNI fix
  become: yes
  apt:
    name:
      - python-pip
      - python-dev
      - libffi-dev
      - libssl-dev
  when:
    - ansible_python_version is version('2.7.9', '<')
    - sansible_elasticsearch_install_sni_fixes

- name: Upgrade Pip for SNI fix
  become: yes
  pip:
    name: pip>=18
  when:
    - ansible_python_version is version('2.7.9', '<')
    - sansible_elasticsearch_install_sni_fixes

- name: Install Python packages for SNI fix
  become: yes
  pip:
    name:
      - pyopenssl>=18.0.0
      - ndg-httpsclient>=0.5.1
      - pyasn1>=0.4.5
  when:
    - ansible_python_version is version('2.7.9', '<')
    - sansible_elasticsearch_install_sni_fixes

- name: Install 1.x Family
  include: install/1.x.yml
  when: sansible_elasticsearch_family == "1.x"

- name: Install 2.x Family
  include: install/2.x.yml
  when: sansible_elasticsearch_family == "2.x"

- name: Install 5.x Family
  include: install/5.x.yml
  when: sansible_elasticsearch_family == "5.x"

- name: Ensure some required directories
  become: yes
  file:
    group: "{{ sansible_elasticsearch_group }}"
    owner: "{{ sansible_elasticsearch_user }}"
    path: "/home/{{ sansible_elasticsearch_user }}/{{ item }}"
    state: directory
  with_items:
    - bin

- name: Ensure Elasticsearch service is enabled
  become: yes
  service:
    name: elasticsearch
    enabled: yes
  when: ansible_distribution_release != "bionic"

- name: Create Elasticsearch startup links
  become: yes
  command: update-rc.d elasticsearch defaults
  args:
    creates: "/etc/rc0.d/K??elasticsearch"
  when: ansible_distribution_release == "bionic"
