---

- name: Install Elasticsearch extra packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ sansible_elasticsearch_packages }}"
  notify: restart elasticsearch

- name: Install 1.x Family
  include: install/1.x.yml
  when: sansible_elasticsearch_family == "1.x"

- name: Install 2.x Family
  include: install/2.x.yml
  when: sansible_elasticsearch_family == "2.x"

- name: Install 5.x Family
  include: install/5.x.yml
  when: sansible_elasticsearch_family == "5.x"

- name: Ensure some required directories
  become: yes
  file:
    group: "{{ sansible_elasticsearch_group }}"
    owner: "{{ sansible_elasticsearch_user }}"
    path: "/home/{{ sansible_elasticsearch_user }}/{{ item }}"
    state: directory
  with_items:
    - bin

- name: Ensure Elasticsearch service is enabled
  become: yes
  service:
    name: elasticsearch
    enabled: yes
