---

- name: Converge
  hosts: all

  pre_tasks:
    - name: Install apt-transport-https, net-tools
      become: yes
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - apt-transport-https
        - net-tools

  roles:
    - role: elasticsearch
      sansible_elasticsearch_additional_config:
        bootstrap.mlockall: yes
        index.number_of_shards: 1
        index.number_of_replicas: 1
        script.groovy.sandbox.enabled: yes
